name: Weekly Idiom

on:
  schedule:
    - cron: '0 1 * * MON'            # Monday 01:00 UTC
  workflow_dispatch:                 # manual run button

jobs:
  make-image:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GH_PAT:         ${{ secrets.GH_PAT }}

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: pip install requests openai pillow

      - name: Run generator
        env:
          GH_PAT: ${{ secrets.GH_PAT }}        # pass it to this step
        run: |
          export GH_PAT="${GH_PAT}"            # make it visible to subprocesses
          python .github/scripts/idiom_bot.py
